spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 30m
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true


---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: aptekarze
    driver-class-name: org.postgresql.Driver
    platform: h2

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 30m
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    datasource:
    username: postgres
    password: GHJbnm123
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver
