spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
    timeout: 30m
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true=username=password
  mail:
    username: ksiazeczkaonlie@gmail.com
    password: GHJbnm123
    host: smtp.gmail.com
    port: 587
    tls: true
  application:
    url: http://localhost:4200
    required:
      activation: false
ksiazeczka:
  quartz:
    deploy: 20
    #      If we set -1 to quartz it will start the task according to the date
    #      if we set a different number then quarz will run the task after this time in second
---
spring:
  profiles: test
  application:
    url: http://localhost:4200
    name: ksiazeczka
    required:
      activation: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: GHJbnm123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
  mvc:
    throw-exception-if-no-handler-found: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    username: ksiazeczkaonlie@gmail.com
    password: GHJbnm123
    host: smtp.gmail.com
    port: 587
    tls: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded
logging:
  level:
    pl.tomekreda: DEBUG
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
ksiazeczka:
  quartz:
    deploy: -1
---
spring:
  profiles: prod
  application:
    url: http://ksiazeczkaonline.pl
    name: ksiazeczka
    required:
      activation: true
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: GHJbnm123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mail:
    username: ksiazeczkaonlie@gmail.com
    password: GHJbnm123
    host: smtp.gmail.com
    port: 587
    tls: true
  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
logging:
  level:
    pl.tomekreda: DEBUG
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
ksiazeczka:
  quartz:
    deploy: -1

