spring:
  profiles:
    active: development
---
spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: aptekarze
    url: jdbc:postgresql://localhost:5432/library
    driver-class-name: org.postgresql.Driver


